<?php
define('ORDER_TEMPLATE_FOR_USER',3);
define('ORDER_TEMPLATE_FOR_ADMIN',4);
define('ACCOUNT_CHANGE_FOR_USER',5);
define('ACCOUNT_CHANGE_FOR_ADMIN',6);
define('QUESTION_FOR_USER',1);
define('QUESTION_FOR_ADMIN',2);
define('ORDER_CHANGE_FOR_USER',7);
define('ORDER_CHANGE_FOR_ADMIN',8);

